[package]
name = "crossterm"
version = "0.3.0"
authors = ["T Post <timonpost@hotmail.nl>"]
description = "An crossplatform terminal library for manipulating terminals."
repository = "https://github.com/TimonPost/crossterm"
documentation = "https://docs.rs/crossterm/"
license = "MIT"
keywords = ["console", "color", "cursor", "terminal", "cli"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase","winuser","consoleapi","processenv","wincon", "handleapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
termios = "0.3.0"

[lib]
name = "crossterm"
path = "src/lib.rs"

#[[bin]]
# name = "example_bin"
# path = "./examples/Crossterm 0.3.1/bin.rs"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "duplex"
path = "examples/duplex.rs"

[[example]]
name = "swap_write"
path = "examples/swap_write.rs"
